In [9]:
import pandas as pd

# Load the CSV file
csv_file_path = './Dataframes/combined_wage_data.csv'
df = pd.read_csv(csv_file_path)

In [10]:
# Ensure the 'Date' column is treated as a string and append '-01'
df['Date'] = df['Date'].astype(str) + '-01'

# Convert 'Date' to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Display the first few rows to check the results
print(df.head())

        Date          Series ID  Value  Inflation Rate            Category
0 2018-01-01  CMU2025100100000D  48.44        0.000000  Total Compensation
1 2018-04-01  CMU2025100100000D  49.08        1.321222  Total Compensation
2 2018-07-01  CMU2025100100000D  49.92        1.711491  Total Compensation
3 2018-10-01  CMU2025100100000D  49.00       -1.842949  Total Compensation
4 2019-01-01  CMU2025100100000D  49.87        1.775510  Total Compensation

In [11]:
print(df['Category'].unique())

['Total Compensation' 'Wages and Salaries' 'Benefits']

In [12]:

# Create the first pivot table for inflation rates
pivot_inflation = df.pivot_table(
    index='Date',
    columns='Category',
    values='Inflation Rate',
    aggfunc='sum',
    fill_value=0
)

# Create the second pivot table for average values
pivot_values = df.pivot_table(
    index='Date',
    columns='Category',
    values='Value',
    aggfunc='mean',
    fill_value=0
)

In [13]:
# Merge the pivot tables on the 'Date' index
combined_pivot = pivot_inflation.merge(pivot_values, on='Date', suffixes=('_Inflation', '_Avg_Value'))

In [14]:
# update columns names to replace spaces with underscores and switch all uppercase letters to lowercase
combined_pivot.columns = combined_pivot.columns.str.replace(" ","_")
combined_pivot.columns = combined_pivot.columns.str.lower()
combined_pivot.index.names  = ["date"]

In [15]:
# Merge the pivot tables on the 'Date' index
combined_pivot

Category,benefits_inflation,total_compensation_inflation,wages_and_salaries_inflation,benefits_avg_value,total_compensation_avg_value,wages_and_salaries_avg_value
date,,,,,,
2018-01-01,0.000000,0.000000,0.000000,23.64,48.44,43.89
2018-04-01,2.411168,1.321222,1.389838,24.21,49.08,44.50
2018-07-01,0.826105,1.711491,1.123596,24.41,49.92,45.00
2018-10-01,-2.580909,-1.842949,-3.311111,23.78,49.00,43.51
2019-01-01,2.060555,1.775510,1.700758,24.27,49.87,44.25
2019-04-01,-3.337454,0.681773,1.107345,23.46,50.21,44.74
2019-07-01,4.987212,0.936069,0.603487,24.63,50.68,45.01
2019-10-01,-5.318717,0.513023,0.266607,23.32,50.94,45.13
2020-01-01,0.814751,-0.235571,0.775537,23.51,50.82,45.48
2020-04-01,0.552956,-0.177096,-0.241865,23.64,50.73,45.37
2020-07-01,0.380711,1.064459,1.013886,23.73,51.27,45.83
2020-10-01,1.432786,-4.251999,-3.142047,24.07,49.09,44.39
2021-01-01,0.166182,2.974129,2.770894,24.11,50.55,45.62
2021-04-01,2.613024,-0.118694,-0.789128,24.74,50.49,45.26
2021-07-01,1.697656,2.337096,4.220062,25.16,51.67,47.17
2021-10-01,2.821940,2.903039,3.837185,25.87,53.17,48.98
2022-01-01,0.541167,2.144066,2.021233,26.01,54.31,49.97
2022-04-01,4.536717,1.252071,0.680408,27.19,54.99,50.31
2022-07-01,2.427363,1.327514,1.689525,27.85,55.72,51.16
2022-10-01,4.524237,3.302225,5.824863,29.11,57.56,54.14
2023-01-01,4.053590,1.424600,1.292944,30.29,58.38,54.84
2023-04-01,0.561241,1.062008,0.929978,30.46,59.00,55.35
2023-07-01,-1.149048,0.237288,0.361337,30.11,59.14,55.55
2023-10-01,7.705081,2.874535,4.932493,32.43,60.84,58.29
2024-01-01,2.096824,1.331361,1.544004,33.11,61.65,59.19

In [17]:
combined_pivot.columns

Index(['benefits_inflation', 'total_compensation_inflation',
       'wages_and_salaries_inflation', 'benefits_avg_value',
       'total_compensation_avg_value', 'wages_and_salaries_avg_value'],
      dtype='object', name='Category')

In [16]:
# Save the combined pivot table to a CSV file
combined_pivot.to_csv('./Resources/Output/z_Wages_pivot.csv')